# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created: Thu Aug 08 09:33:25 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

import images_rc
from PySide import QtCore, QtGui

class Ui_menuBackground(object):
    def setupUi(self, menuBackground):
        self.setObjectName("menuBackground")
        self.setEnabled(True)
        self.resize(93, 336)
        self.setMouseTracking(True)
        self.setAutoFillBackground(True)
        self.setStyleSheet("")
        self.gridlayout = QtGui.QGridLayout(self)
        self.gridlayout.setObjectName("gridlayout")
        self.constellationButton = QtGui.QPushButton(self)
        self.constellationButton.setMinimumSize(QtCore.QSize(40, 40))
        self.constellationButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/drawable/stars_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.constellationButton.setIcon(icon)
        self.constellationButton.setIconSize(QtCore.QSize(40, 40))
        self.constellationButton.setFlat(True)
        self.constellationButton.setObjectName("constellationButton")
        self.gridlayout.addWidget(self.constellationButton, 1, 0, 1, 1)
        self.starButton = QtGui.QPushButton(self)
        self.starButton.setMinimumSize(QtCore.QSize(40, 40))
        self.starButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assets/drawable/star_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.starButton.setIcon(icon1)
        self.starButton.setIconSize(QtCore.QSize(40, 40))
        self.starButton.setFlat(True)
        self.starButton.setObjectName("starButton")
        self.gridlayout.addWidget(self.starButton, 0, 0, 1, 1)
        self.gridButton = QtGui.QPushButton(self)
        self.gridButton.setMinimumSize(QtCore.QSize(40, 40))
        self.gridButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/assets/drawable/grid_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gridButton.setIcon(icon2)
        self.gridButton.setIconSize(QtCore.QSize(40, 40))
        self.gridButton.setFlat(True)
        self.gridButton.setObjectName("gridButton")
        self.gridlayout.addWidget(self.gridButton, 5, 0, 1, 1)
        self.horizonButton = QtGui.QPushButton(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizonButton.sizePolicy().hasHeightForWidth())
        self.horizonButton.setSizePolicy(sizePolicy)
        self.horizonButton.setMinimumSize(QtCore.QSize(40, 40))
        self.horizonButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/assets/drawable/horizon_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.horizonButton.setIcon(icon3)
        self.horizonButton.setIconSize(QtCore.QSize(40, 40))
        self.horizonButton.setFlat(True)
        self.horizonButton.setObjectName("horizonButton")
        self.gridlayout.addWidget(self.horizonButton, 6, 0, 1, 1)
        self.planetsButton = QtGui.QPushButton(self)
        self.planetsButton.setMinimumSize(QtCore.QSize(40, 40))
        self.planetsButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/assets/drawable/planet_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.planetsButton.setIcon(icon4)
        self.planetsButton.setIconSize(QtCore.QSize(40, 40))
        self.planetsButton.setFlat(True)
        self.planetsButton.setObjectName("planetsButton")
        self.gridlayout.addWidget(self.planetsButton, 3, 0, 1, 1)
        self.messierButton = QtGui.QPushButton(self)
        self.messierButton.setMinimumSize(QtCore.QSize(40, 40))
        self.messierButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/assets/drawable/messier_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messierButton.setIcon(icon5)
        self.messierButton.setIconSize(QtCore.QSize(40, 40))
        self.messierButton.setFlat(True)
        self.messierButton.setObjectName("messierButton")
        self.gridlayout.addWidget(self.messierButton, 2, 0, 1, 1)
        self.meteorButton = QtGui.QPushButton(self)
        self.meteorButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/assets/drawable/b_meteor_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.meteorButton.setIcon(icon6)
        self.meteorButton.setIconSize(QtCore.QSize(40, 40))
        self.meteorButton.setFlat(True)
        self.meteorButton.setObjectName("meteorButton")
        self.gridlayout.addWidget(self.meteorButton, 4, 0, 1, 1)

        self.retranslateUi(self)

    def retranslateUi(self, menuBackground):
        self.setWindowTitle(QtGui.QApplication.translate("menuBackground", "Widget", None, QtGui.QApplication.UnicodeUTF8))
